# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52be9841fda60ac8651617d70224dc4dead89688d7a4fab93a33c7c1e6251a4782430bcd81f4f9c16084042f7c481ac965fbeff687c34b7075f5f5bc0e7deb25

test:
  secret_key_base: 8a9804c851e6962fac4281bdc6937810e87d082589eef8cda70fec4b5effadbde132bd0c17b5a21e302e5acc62207f2a7d2dbc2bda4edf67bc9c4fdd711c5c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
